/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Категории каталога с числом активных товаров */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            slug: string;
                            name: {
                                ru: string;
                                kk: string;
                            };
                            description: {
                                ru: string | null;
                                kk: string | null;
                            };
                            image: {
                                id: string;
                                url: string;
                                width: number;
                                height: number;
                                lqip: string | null;
                                alt: {
                                    ru: string | null;
                                    kk: string | null;
                                };
                            } | null;
                            productCount?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список товаров с фильтрами */
        get: {
            parameters: {
                query?: {
                    category?: string;
                    search?: string;
                    type?: "SIMPLE" | "BUNDLE";
                    featured?: boolean;
                    sort?: "default" | "price_asc" | "price_desc" | "name" | "new";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                id: string;
                                slug: string;
                                /** @enum {string} */
                                type: "SIMPLE" | "BUNDLE";
                                name: {
                                    ru: string;
                                    kk: string;
                                };
                                short: {
                                    ru: string | null;
                                    kk: string | null;
                                };
                                price: number;
                                compareAtPrice: number | null;
                                weight: {
                                    value: number;
                                    /** @enum {string} */
                                    unit: "G" | "ML" | "PORTION" | "PCS";
                                };
                                /** @enum {string} */
                                stockStatus: "IN_STOCK" | "LOW" | "OUT";
                                isFeatured: boolean;
                                category: {
                                    id: string;
                                    slug: string;
                                    name: {
                                        ru: string;
                                        kk: string;
                                    };
                                } | null;
                                badges: {
                                    code: string;
                                    label: {
                                        ru: string;
                                        kk: string;
                                    };
                                    /** @enum {string} */
                                    tone: "GOLD" | "TEAL" | "STONE";
                                    icon: string | null;
                                }[];
                                image: {
                                    id: string;
                                    url: string;
                                    width: number;
                                    height: number;
                                    lqip: string | null;
                                    alt: {
                                        ru: string | null;
                                        kk: string | null;
                                    };
                                } | null;
                            }[];
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка товара: все фото, описание, состав набора */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            slug: string;
                            /** @enum {string} */
                            type: "SIMPLE" | "BUNDLE";
                            name: {
                                ru: string;
                                kk: string;
                            };
                            short: {
                                ru: string | null;
                                kk: string | null;
                            };
                            price: number;
                            compareAtPrice: number | null;
                            weight: {
                                value: number;
                                /** @enum {string} */
                                unit: "G" | "ML" | "PORTION" | "PCS";
                            };
                            /** @enum {string} */
                            stockStatus: "IN_STOCK" | "LOW" | "OUT";
                            isFeatured: boolean;
                            category: {
                                id: string;
                                slug: string;
                                name: {
                                    ru: string;
                                    kk: string;
                                };
                            } | null;
                            badges: {
                                code: string;
                                label: {
                                    ru: string;
                                    kk: string;
                                };
                                /** @enum {string} */
                                tone: "GOLD" | "TEAL" | "STONE";
                                icon: string | null;
                            }[];
                            image: {
                                id: string;
                                url: string;
                                width: number;
                                height: number;
                                lqip: string | null;
                                alt: {
                                    ru: string | null;
                                    kk: string | null;
                                };
                            } | null;
                            description: {
                                ru: string | null;
                                kk: string | null;
                            };
                            seoTitle: {
                                ru: string | null;
                                kk: string | null;
                            };
                            seoDescription: {
                                ru: string | null;
                                kk: string | null;
                            };
                            images: {
                                id: string;
                                url: string;
                                width: number;
                                height: number;
                                lqip: string | null;
                                alt: {
                                    ru: string | null;
                                    kk: string | null;
                                };
                            }[];
                            bundleItems: {
                                qty: number;
                                product: {
                                    id: string;
                                    slug: string;
                                    /** @enum {string} */
                                    type: "SIMPLE" | "BUNDLE";
                                    name: {
                                        ru: string;
                                        kk: string;
                                    };
                                    short: {
                                        ru: string | null;
                                        kk: string | null;
                                    };
                                    price: number;
                                    compareAtPrice: number | null;
                                    weight: {
                                        value: number;
                                        /** @enum {string} */
                                        unit: "G" | "ML" | "PORTION" | "PCS";
                                    };
                                    /** @enum {string} */
                                    stockStatus: "IN_STOCK" | "LOW" | "OUT";
                                    isFeatured: boolean;
                                    category: {
                                        id: string;
                                        slug: string;
                                        name: {
                                            ru: string;
                                            kk: string;
                                        };
                                    } | null;
                                    badges: {
                                        code: string;
                                        label: {
                                            ru: string;
                                            kk: string;
                                        };
                                        /** @enum {string} */
                                        tone: "GOLD" | "TEAL" | "STONE";
                                        icon: string | null;
                                    }[];
                                    image: {
                                        id: string;
                                        url: string;
                                        width: number;
                                        height: number;
                                        lqip: string | null;
                                        alt: {
                                            ru: string | null;
                                            kk: string | null;
                                        };
                                    } | null;
                                };
                            }[];
                            componentsTotal: number | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/collections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Подборка товаров («Хиты», «Новинки» и т.д.) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            slug: string;
                            title: {
                                ru: string;
                                kk: string;
                            };
                            subtitle: {
                                ru: string | null;
                                kk: string | null;
                            };
                            products: {
                                id: string;
                                slug: string;
                                /** @enum {string} */
                                type: "SIMPLE" | "BUNDLE";
                                name: {
                                    ru: string;
                                    kk: string;
                                };
                                short: {
                                    ru: string | null;
                                    kk: string | null;
                                };
                                price: number;
                                compareAtPrice: number | null;
                                weight: {
                                    value: number;
                                    /** @enum {string} */
                                    unit: "G" | "ML" | "PORTION" | "PCS";
                                };
                                /** @enum {string} */
                                stockStatus: "IN_STOCK" | "LOW" | "OUT";
                                isFeatured: boolean;
                                category: {
                                    id: string;
                                    slug: string;
                                    name: {
                                        ru: string;
                                        kk: string;
                                    };
                                } | null;
                                badges: {
                                    code: string;
                                    label: {
                                        ru: string;
                                        kk: string;
                                    };
                                    /** @enum {string} */
                                    tone: "GOLD" | "TEAL" | "STONE";
                                    icon: string | null;
                                }[];
                                image: {
                                    id: string;
                                    url: string;
                                    width: number;
                                    height: number;
                                    lqip: string | null;
                                    alt: {
                                        ru: string | null;
                                        kk: string | null;
                                    };
                                } | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Секции главной страницы и публичные настройки одним запросом */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sections: {
                                id: string;
                                /** @enum {string} */
                                kind: "HERO" | "COLLECTION" | "BUNDLES" | "CATEGORIES" | "EDITORIAL" | "BANNER" | "STEPS" | "FAQ" | "CONTACTS";
                                payload: {
                                    [key: string]: unknown;
                                };
                                sortOrder: number;
                                products?: {
                                    id: string;
                                    slug: string;
                                    /** @enum {string} */
                                    type: "SIMPLE" | "BUNDLE";
                                    name: {
                                        ru: string;
                                        kk: string;
                                    };
                                    short: {
                                        ru: string | null;
                                        kk: string | null;
                                    };
                                    price: number;
                                    compareAtPrice: number | null;
                                    weight: {
                                        value: number;
                                        /** @enum {string} */
                                        unit: "G" | "ML" | "PORTION" | "PCS";
                                    };
                                    /** @enum {string} */
                                    stockStatus: "IN_STOCK" | "LOW" | "OUT";
                                    isFeatured: boolean;
                                    category: {
                                        id: string;
                                        slug: string;
                                        name: {
                                            ru: string;
                                            kk: string;
                                        };
                                    } | null;
                                    badges: {
                                        code: string;
                                        label: {
                                            ru: string;
                                            kk: string;
                                        };
                                        /** @enum {string} */
                                        tone: "GOLD" | "TEAL" | "STONE";
                                        icon: string | null;
                                    }[];
                                    image: {
                                        id: string;
                                        url: string;
                                        width: number;
                                        height: number;
                                        lqip: string | null;
                                        alt: {
                                            ru: string | null;
                                            kk: string | null;
                                        };
                                    } | null;
                                }[];
                            }[];
                            settings: {
                                contacts: {
                                    phone: string;
                                    whatsapp: string;
                                    telegram: string;
                                    instagram: string;
                                    email: string;
                                    address: {
                                        ru: string;
                                        kk: string;
                                    };
                                    workingHours: {
                                        ru: string;
                                        kk: string;
                                    };
                                };
                                delivery: {
                                    minOrder: number;
                                    baseFee: number;
                                    freeFrom: number | null;
                                    pickupAddress: {
                                        ru: string;
                                        kk: string;
                                    };
                                    note: {
                                        ru: string;
                                        kk: string;
                                    };
                                };
                                brand: {
                                    name: string;
                                    tagline: {
                                        ru: string;
                                        kk: string;
                                    };
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Контакты, доставка, бренд — всё, что нужно шапке и подвалу */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            contacts: {
                                phone: string;
                                whatsapp: string;
                                telegram: string;
                                instagram: string;
                                email: string;
                                address: {
                                    ru: string;
                                    kk: string;
                                };
                                workingHours: {
                                    ru: string;
                                    kk: string;
                                };
                            };
                            delivery: {
                                minOrder: number;
                                baseFee: number;
                                freeFrom: number | null;
                                pickupAddress: {
                                    ru: string;
                                    kk: string;
                                };
                                note: {
                                    ru: string;
                                    kk: string;
                                };
                            };
                            brand: {
                                name: string;
                                tagline: {
                                    ru: string;
                                    kk: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Оформление заказа: сохраняет заявку и отдаёт ссылку в чат */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        customerName: string;
                        phone: string;
                        /**
                         * @default WHATSAPP
                         * @enum {string}
                         */
                        channel?: "WHATSAPP" | "TELEGRAM";
                        /**
                         * @default PERSON
                         * @enum {string}
                         */
                        customerType?: "PERSON" | "BUSINESS";
                        /**
                         * @default DELIVERY
                         * @enum {string}
                         */
                        deliveryType?: "DELIVERY" | "PICKUP";
                        address?: string;
                        comment?: string;
                        /**
                         * @default ru
                         * @enum {string}
                         */
                        locale?: "ru" | "kk";
                        items: {
                            productId: string;
                            qty: number;
                        }[];
                        website?: string;
                        /** @default false */
                        isTest?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            number: string;
                            status: string;
                            subtotal: number;
                            deliveryFee: number;
                            total: number;
                            chatUrl: string;
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
